Nodo ESP32 MPU6050 + microSD: main/file_logger.c File Reference
file_logger.c File Reference
Implementación del módulo encargado de registrar datos en archivo.
#include "file_logger.h"
#include "sdcard_drv.h"
#include "config.h"
#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include <sys/stat.h>
#include "esp_log.h"
Functions
esp_err_t file_logger_init (void)
Inicializa el archivo de log en la microSD.
esp_err_t file_logger_write_record (const log_record_t *record)
Escribe un registro formateado en el archivo de log.
void file_logger_close (void)
Cierra el archivo de log actualmente abierto.
Variables
static const char * TAG = "FILE_LOGGER"
Etiqueta usada para mensajes de depuración del módulo.
static FILE * g_log_file = NULL
Puntero global al archivo de log actualmente abierto.
Detailed Description
Implementación del módulo encargado de registrar datos en archivo.
Este módulo administra la apertura del archivo de log en la microSD y la escritura de los registros generados por el sistema. Su objetivo es separar la lógica de almacenamiento de la lógica de adquisición y procesamiento de datos del MPU6050.
La idea general es:
verificar que la microSD esté montada,
abrir el archivo de salida,
escribir el encabezado solo si el archivo está vacío,
y luego agregar cada nuevo registro que llegue desde las tareas del sistema.
Definition in file file_logger.c.
Function Documentation
file_logger_close()
void file_logger_close (void)
Cierra el archivo de log actualmente abierto.
Esta función libera el recurso asociado al archivo si se encuentra abierto y reinicia el puntero global a NULL para evitar accesos inválidos.
Se utiliza cuando se quiere finalizar de forma segura la sesión de escritura sobre la microSD.
Definition at line 135 of file file_logger.c.
References g_log_file, and sdcard_close_file().
file_logger_init()
esp_err_t file_logger_init (void)
Inicializa el archivo de log en la microSD.
Inicializa el módulo de escritura en archivo.
Esta función comprueba primero que la tarjeta SD esté montada. Después verifica si el archivo ya existe y si contiene información, usando stat(). Si el archivo está vacío, escribe el encabezado con los nombres de las columnas; si ya contiene datos, simplemente lo abre para seguir agregando registros al final.
Su lógica permite que el archivo conserve información previa y evita duplicar el encabezado en cada reinicio del sistema.
Returns
ESP_OK si el archivo quedó listo para escritura.
ESP_FAIL si la SD no está montada, si el archivo no pudo abrirse o si falló la escritura del encabezado.
Definition at line 55 of file file_logger.c.
References g_log_file, LOG_FILE_PATH, sdcard_append_line(), sdcard_close_file(), sdcard_is_mounted(), sdcard_open_log_file(), and TAG.
Referenced by sd_writer_task().
file_logger_write_record()
esp_err_t file_logger_write_record (const log_record_t * record)
Escribe un registro formateado en el archivo de log.
Esta función recibe un registro ya convertido a texto y lo agrega al archivo abierto en la microSD. Antes de escribir, valida que el puntero al registro sea válido y que el archivo haya sido inicializado correctamente.
Su lógica es delegar la escritura real al driver de la SD, manteniendo este módulo como intermediario entre la aplicación y el sistema de archivos.
Parameters
record Puntero al registro que contiene la línea de texto a guardar.
Returns
ESP_OK si el registro fue escrito correctamente.
ESP_ERR_INVALID_ARG si el puntero recibido es nulo.
ESP_FAIL si el archivo no está abierto o si ocurre un error de escritura.
Definition at line 111 of file file_logger.c.
References g_log_file, log_record_t::line, sdcard_append_line(), and TAG.
Referenced by sd_writer_task().
Variable Documentation
g_log_file
FILE* g_log_file = NULL static
Puntero global al archivo de log actualmente abierto.
Esta variable mantiene abierto el archivo para evitar estar abriendo y cerrando el recurso en cada escritura.
Definition at line 36 of file file_logger.c.
Referenced by file_logger_close(), file_logger_init(), and file_logger_write_record().
TAG
const char* TAG = "FILE_LOGGER" static
Etiqueta usada para mensajes de depuración del módulo.
Definition at line 28 of file file_logger.c.
Referenced by app_main(), file_logger_init(), file_logger_write_record(), mpu6050_init(), sdcard_append_line(), sdcard_init(), sdcard_open_log_file(), sdcard_self_test(), task_manager_create_tasks(), and task_manager_init().