Nodo ESP32 MPU6050 + microSD: main/mpu6050_drv.c File Reference
mpu6050_drv.c File Reference
Implementación del driver básico para el sensor MPU6050.
#include "mpu6050_drv.h"
#include "config.h"
#include <string.h>
#include "driver/i2c.h"
#include "esp_log.h"
#include "esp_timer.h"
Macros
#define MPU6050_REG_WHO_AM_I 0x75
Dirección del registro WHO_AM_I del MPU6050.
#define MPU6050_REG_PWR_MGMT_1 0x6B
Dirección del registro de gestión de energía 1.
#define MPU6050_REG_ACCEL_XOUT_H 0x3B
Dirección inicial del bloque de datos del acelerómetro.
#define MPU6050_WHO_AM_I_EXPECTED 0x68
Valor esperado en el registro WHO_AM_I para un MPU6050.
Functions
static esp_err_t mpu6050_write_byte (uint8_t reg_addr, uint8_t data)
Escribe un byte en un registro interno del MPU6050.
static esp_err_t mpu6050_read_bytes (uint8_t reg_addr, uint8_t *data, size_t len)
Lee uno o varios bytes desde un registro del MPU6050.
static esp_err_t mpu6050_i2c_master_init (void)
Inicializa el bus I2C maestro usado por el MPU6050.
esp_err_t mpu6050_init (void)
Inicializa el sensor MPU6050.
esp_err_t mpu6050_read_raw (mpu_raw_data_t *out_data)
Lee una muestra cruda del MPU6050 y la convierte a unidades físicas.
Variables
static const char * TAG = "MPU6050"
Etiqueta usada para mensajes de depuración del módulo MPU6050.
Detailed Description
Implementación del driver básico para el sensor MPU6050.
Este módulo se encarga de inicializar la comunicación I2C con el MPU6050, verificar la presencia del sensor, despertarlo desde su estado de reposo y leer sus registros principales de aceleración, giroscopio y temperatura.
La lógica general del driver es:
configurar el bus I2C del ESP32,
leer el registro WHO_AM_I para validar la respuesta del sensor,
escribir en PWR_MGMT_1 para activar el MPU6050,
leer los 14 bytes consecutivos de datos crudos,
y convertir esos valores a unidades físicas utilizables por el resto del sistema.
Definition in file mpu6050_drv.c.
Macro Definition Documentation
MPU6050_REG_ACCEL_XOUT_H
#define MPU6050_REG_ACCEL_XOUT_H 0x3B
Dirección inicial del bloque de datos del acelerómetro.
A partir de este registro se leen en secuencia los datos de aceleración, temperatura y giroscopio.
Definition at line 54 of file mpu6050_drv.c.
Referenced by mpu6050_read_raw().
MPU6050_REG_PWR_MGMT_1
#define MPU6050_REG_PWR_MGMT_1 0x6B
Dirección del registro de gestión de energía 1.
Se utiliza para sacar al sensor del modo sleep y dejarlo operativo.
Definition at line 46 of file mpu6050_drv.c.
Referenced by mpu6050_init().
MPU6050_REG_WHO_AM_I
#define MPU6050_REG_WHO_AM_I 0x75
Dirección del registro WHO_AM_I del MPU6050.
Este registro permite verificar la identidad del dispositivo conectado al bus I2C.
Definition at line 39 of file mpu6050_drv.c.
Referenced by mpu6050_init().
MPU6050_WHO_AM_I_EXPECTED
#define MPU6050_WHO_AM_I_EXPECTED 0x68
Valor esperado en el registro WHO_AM_I para un MPU6050.
Definition at line 59 of file mpu6050_drv.c.
Referenced by mpu6050_init().
Function Documentation
mpu6050_i2c_master_init()
esp_err_t mpu6050_i2c_master_init (void) static
Inicializa el bus I2C maestro usado por el MPU6050.
Esta función configura el periférico I2C del ESP32 en modo maestro usando los pines y parámetros definidos en el archivo de configuración del proyecto. Después aplica la configuración e instala el driver I2C.
Su lógica deja lista la capa física de comunicación antes de interactuar con cualquier registro del sensor.
Returns
ESP_OK si la configuración e instalación del bus fueron correctas.
Código de error si la configuración del puerto o la instalación del driver falla.
Definition at line 134 of file mpu6050_drv.c.
References I2C_MASTER_FREQ_HZ, I2C_MASTER_NUM, I2C_MASTER_SCL_IO, and I2C_MASTER_SDA_IO.
Referenced by mpu6050_init().
mpu6050_init()
esp_err_t mpu6050_init (void)
Inicializa el sensor MPU6050.
Esta función prepara tanto la interfaz I2C como el propio sensor. Primero inicializa el bus maestro, luego lee el registro WHO_AM_I para comprobar la respuesta del dispositivo y finalmente escribe en PWR_MGMT_1 para sacar al MPU6050 del modo sleep.
La lógica de esta función garantiza que el sensor quede listo para comenzar a entregar datos crudos de aceleración, giroscopio y temperatura.
Returns
ESP_OK si el sensor fue inicializado correctamente.
Código de error si falla la inicialización del bus, la lectura de identificación o la escritura del registro de activación.
Definition at line 170 of file mpu6050_drv.c.
References mpu6050_i2c_master_init(), mpu6050_read_bytes(), MPU6050_REG_PWR_MGMT_1, MPU6050_REG_WHO_AM_I, MPU6050_WHO_AM_I_EXPECTED, mpu6050_write_byte(), and TAG.
Referenced by app_main().
mpu6050_read_bytes()
esp_err_t mpu6050_read_bytes (uint8_t reg_addr, uint8_t * data, size_t len) static
Lee uno o varios bytes desde un registro del MPU6050.
Esta función auxiliar primero envía la dirección del registro deseado y luego realiza una lectura consecutiva de la cantidad de bytes indicada.
Se utiliza tanto para consultar registros de identificación como para leer el bloque completo de datos del sensor.
Parameters
reg_addr Dirección del registro inicial de lectura.
data Puntero al buffer donde se almacenarán los datos leídos.
len Cantidad de bytes a leer.
Returns
ESP_OK si la lectura fue exitosa.
Código de error de ESP-IDF si la transacción I2C falla.
Definition at line 107 of file mpu6050_drv.c.
References I2C_MASTER_NUM, I2C_MASTER_TIMEOUT_MS, and MPU6050_I2C_ADDR.
Referenced by mpu6050_init(), and mpu6050_read_raw().
mpu6050_read_raw()
esp_err_t mpu6050_read_raw (mpu_raw_data_t * out_data)
Lee una muestra cruda del MPU6050 y la convierte a unidades físicas.
Lee una muestra del MPU6050 y la almacena en una estructura de salida.
Esta función realiza una lectura continua de 14 bytes desde el registro ACCEL_XOUT_H. A partir de ese bloque obtiene:
aceleración en los ejes X, Y y Z,
temperatura interna,
velocidad angular en los ejes X, Y y Z.
Luego interpreta los bytes como enteros de 16 bits con signo y aplica los factores de escala por defecto del sensor al arrancar:
acelerómetro en rango ±2g,
giroscopio en rango ±250 °/s.
Finalmente también agrega una marca de tiempo en milisegundos usando el temporizador del sistema.
Parameters
out_data Puntero a la estructura donde se guardará la muestra convertida.
Returns
ESP_OK si la lectura y conversión fueron exitosas.
ESP_ERR_INVALID_ARG si el puntero de salida es nulo.
Código de error si la lectura I2C falla.
Definition at line 228 of file mpu6050_drv.c.
References mpu_raw_data_t::ax, mpu_raw_data_t::ay, mpu_raw_data_t::az, mpu_raw_data_t::gx, mpu_raw_data_t::gy, mpu_raw_data_t::gz, mpu6050_read_bytes(), MPU6050_REG_ACCEL_XOUT_H, mpu_raw_data_t::temperature, and mpu_raw_data_t::timestamp_ms.
Referenced by sensor_task().
mpu6050_write_byte()
esp_err_t mpu6050_write_byte (uint8_t reg_addr, uint8_t data) static
Escribe un byte en un registro interno del MPU6050.
Esta función auxiliar construye un pequeño buffer con la dirección del registro y el dato a escribir, y luego lo transmite mediante I2C.
Su lógica se usa principalmente durante la inicialización del sensor, por ejemplo para modificar registros de control como PWR_MGMT_1.
Parameters
reg_addr Dirección del registro a modificar.
data Dato de 8 bits que se desea escribir.
Returns
ESP_OK si la escritura fue exitosa.
Código de error de ESP-IDF si la transacción I2C falla.
Definition at line 77 of file mpu6050_drv.c.
References I2C_MASTER_NUM, I2C_MASTER_TIMEOUT_MS, and MPU6050_I2C_ADDR.
Referenced by mpu6050_init().
Variable Documentation
TAG
const char* TAG = "MPU6050" static
Etiqueta usada para mensajes de depuración del módulo MPU6050.
Definition at line 26 of file mpu6050_drv.c.