Nodo ESP32 MPU6050 + microSD: main/task_manager.c File Reference
task_manager.c File Reference
Implementación del gestor de colas y tareas de FreeRTOS.
#include "task_manager.h"
#include "config.h"
#include "data_types.h"
#include "mpu6050_drv.h"
#include "file_logger.h"
#include <stdio.h>
#include <string.h>
#include <math.h>
#include "freertos/task.h"
#include "esp_log.h"
Macros
#define M_PI 3.14159265358979323846
#define RAD_TO_DEG (180.0f / (float)M_PI)
Factor de conversión de radianes a grados.
Functions
static void sensor_task (void *pvParameters)
Tarea encargada de leer periódicamente el MPU6050.
static void format_local_task (void *pvParameters)
Tarea encargada de procesar las muestras del MPU6050 y formatearlas.
static void sd_writer_task (void *pvParameters)
Tarea encargada de escribir registros en la microSD.
esp_err_t task_manager_init (void)
Inicializa las colas de comunicación del sistema.
esp_err_t task_manager_create_tasks (void)
Crea las tareas principales del sistema.
Variables
QueueHandle_t g_raw_queue = NULL
Cola que transporta muestras crudas del MPU6050.
QueueHandle_t g_log_queue = NULL
Cola que transporta registros listos para guardar.
static const char * TAG = "TASK_MANAGER"
Etiqueta usada para mensajes de depuración del gestor de tareas.
Detailed Description
Implementación del gestor de colas y tareas de FreeRTOS.
Este módulo coordina el flujo principal de procesamiento del nodo. Su función es crear las colas de comunicación entre tareas y lanzar las tareas que componen la lógica del sistema.
La secuencia general de trabajo es:
una tarea lee periódicamente el MPU6050,
otra tarea toma esos datos y calcula pitch y roll,
una tercera tarea recibe los registros ya formateados y los escribe en la SD.
De esta manera se separa la adquisición, el procesamiento y el almacenamiento, logrando un diseño más ordenado y fácil de depurar.
Definition in file task_manager.c.
Macro Definition Documentation
M_PI
#define M_PI 3.14159265358979323846
Definition at line 32 of file task_manager.c.
RAD_TO_DEG
#define RAD_TO_DEG (180.0f / (float)M_PI)
Factor de conversión de radianes a grados.
Se utiliza para transformar el resultado de las funciones trigonométricas al calcular pitch y roll.
Definition at line 41 of file task_manager.c.
Referenced by format_local_task().
Function Documentation
format_local_task()
void format_local_task (void * pvParameters) static
Tarea encargada de procesar las muestras del MPU6050 y formatearlas.
Esta tarea consume datos desde g_raw_queue. Cada vez que recibe una muestra, calcula los ángulos de pitch y roll usando los valores de aceleración y luego construye una línea de texto lista para ser almacenada en archivo.
La lógica de esta tarea es convertir la información numérica cruda en un registro estructurado de texto, desacoplando así el procesamiento matemático de la etapa de escritura en la microSD.
Parameters
pvParameters Parámetro genérico de FreeRTOS, no utilizado en esta tarea.
Definition at line 117 of file task_manager.c.
References mpu_raw_data_t::ax, mpu_raw_data_t::ay, mpu_raw_data_t::az, g_log_queue, g_raw_queue, mpu_raw_data_t::gx, mpu_raw_data_t::gy, mpu_raw_data_t::gz, log_record_t::line, RAD_TO_DEG, mpu_raw_data_t::temperature, log_record_t::timestamp_ms, and mpu_raw_data_t::timestamp_ms.
Referenced by task_manager_create_tasks().
sd_writer_task()
void sd_writer_task (void * pvParameters) static
Tarea encargada de escribir registros en la microSD.
Esta tarea inicializa primero el módulo file_logger y luego queda bloqueada esperando registros en la cola g_log_queue. Cada registro recibido se envía al módulo de escritura para ser almacenado en el archivo de log.
Su lógica es funcionar como consumidor final del pipeline del sistema, recibiendo registros ya formateados y delegando la escritura física al módulo de almacenamiento.
Parameters
pvParameters Parámetro genérico de FreeRTOS, no utilizado en esta tarea.
Definition at line 173 of file task_manager.c.
References file_logger_init(), file_logger_write_record(), g_log_queue, and log_record_t::timestamp_ms.
Referenced by task_manager_create_tasks().
sensor_task()
void sensor_task (void * pvParameters) static
Tarea encargada de leer periódicamente el MPU6050.
Esta tarea ejecuta la adquisición local del sensor. En cada iteración intenta obtener una nueva muestra del MPU6050 y, si la lectura es correcta, envía esa muestra a la cola g_raw_queue.
Su lógica es actuar como productor de datos crudos dentro del sistema. Usa vTaskDelayUntil() para mantener un periodo de muestreo constante definido por SENSOR_SAMPLE_PERIOD_MS.
Parameters
pvParameters Parámetro genérico de FreeRTOS, no utilizado en esta tarea.
Definition at line 75 of file task_manager.c.
References mpu_raw_data_t::ax, mpu_raw_data_t::ay, mpu_raw_data_t::az, g_raw_queue, mpu6050_read_raw(), and SENSOR_SAMPLE_PERIOD_MS.
Referenced by task_manager_create_tasks().
task_manager_create_tasks()
esp_err_t task_manager_create_tasks (void)
Crea las tareas principales del sistema.
Crea las tareas principales del nodo.
Esta función lanza las tres tareas que componen la lógica operativa del nodo:
sensor_task para adquisición del MPU6050,
format_local_task para cálculo y formateo,
sd_writer_task para escritura en microSD.
La lógica de creación sigue el orden natural del flujo de datos, de manera que el sistema quede listo para capturar, procesar y almacenar información de forma continua.
Returns
ESP_OK si todas las tareas fueron creadas correctamente.
ESP_FAIL si falla la creación de alguna tarea.
Definition at line 254 of file task_manager.c.
References format_local_task(), FORMAT_TASK_PRIORITY, FORMAT_TASK_STACK, SD_TASK_PRIORITY, SD_TASK_STACK, sd_writer_task(), sensor_task(), SENSOR_TASK_PRIORITY, SENSOR_TASK_STACK, and TAG.
Referenced by app_main().
task_manager_init()
esp_err_t task_manager_init (void)
Inicializa las colas de comunicación del sistema.
Inicializa las colas principales del sistema.
Esta función crea las dos colas principales usadas por el pipeline del nodo: una para transportar muestras crudas del sensor y otra para transportar registros listos para almacenamiento.
La lógica de esta inicialización es dejar preparados los canales de comunicación antes de lanzar cualquier tarea, evitando que una tarea empiece a ejecutarse sin que sus recursos de intercambio existan.
Returns
ESP_OK si ambas colas fueron creadas correctamente.
ESP_FAIL si alguna de las colas no pudo crearse.
Definition at line 220 of file task_manager.c.
References g_log_queue, g_raw_queue, LOG_QUEUE_LENGTH, RAW_QUEUE_LENGTH, and TAG.
Referenced by app_main().
Variable Documentation
g_log_queue
QueueHandle_t g_log_queue = NULL
Cola que transporta registros listos para guardar.
Cola global para transportar registros listos para almacenamiento.
En esta cola la tarea de formateo deposita estructuras del tipo log_record_t, ya convertidas a texto, para que la tarea de escritura las almacene en la SD.
Definition at line 57 of file task_manager.c.
Referenced by format_local_task(), sd_writer_task(), and task_manager_init().
g_raw_queue
QueueHandle_t g_raw_queue = NULL
Cola que transporta muestras crudas del MPU6050.
Cola global para transportar muestras crudas del MPU6050.
En esta cola la tarea de lectura del sensor deposita estructuras del tipo mpu_raw_data_t para que luego sean procesadas por la tarea de formateo.
Definition at line 49 of file task_manager.c.
Referenced by format_local_task(), sensor_task(), and task_manager_init().
TAG
const char* TAG = "TASK_MANAGER" static
Etiqueta usada para mensajes de depuración del gestor de tareas.
Definition at line 60 of file task_manager.c.