Nodo ESP32 MPU6050 + microSD: main/task_manager.h File Reference
task_manager.h File Reference
Interfaz pública del gestor de tareas y colas del sistema.
#include "freertos/FreeRTOS.h"
#include "freertos/queue.h"
#include "esp_err.h"
Functions
esp_err_t task_manager_init (void)
Inicializa las colas principales del sistema.
esp_err_t task_manager_create_tasks (void)
Crea las tareas principales del nodo.
Variables
QueueHandle_t g_raw_queue
Cola global para transportar muestras crudas del MPU6050.
QueueHandle_t g_log_queue
Cola global para transportar registros listos para almacenamiento.
Detailed Description
Interfaz pública del gestor de tareas y colas del sistema.
Este archivo declara los recursos globales y las funciones encargadas de preparar la arquitectura multitarea del proyecto basada en FreeRTOS.
El módulo task_manager organiza el flujo principal del nodo mediante colas y tareas independientes, permitiendo separar la lectura del MPU6050, el procesamiento de datos y la escritura en la microSD.
Definition in file task_manager.h.
Function Documentation
task_manager_create_tasks()
esp_err_t task_manager_create_tasks (void)
Crea las tareas principales del nodo.
Esta función lanza las tareas encargadas de la lectura del sensor, el procesamiento de los datos y la escritura en la microSD.
Debe llamarse después de que las colas y los módulos base del sistema hayan sido inicializados correctamente.
Returns
ESP_OK si todas las tareas fueron creadas con éxito.
ESP_FAIL si alguna tarea no pudo crearse.
Crea las tareas principales del nodo.
Esta función lanza las tres tareas que componen la lógica operativa del nodo:
sensor_task para adquisición del MPU6050,
format_local_task para cálculo y formateo,
sd_writer_task para escritura en microSD.
La lógica de creación sigue el orden natural del flujo de datos, de manera que el sistema quede listo para capturar, procesar y almacenar información de forma continua.
Returns
ESP_OK si todas las tareas fueron creadas correctamente.
ESP_FAIL si falla la creación de alguna tarea.
Definition at line 254 of file task_manager.c.
References format_local_task(), FORMAT_TASK_PRIORITY, FORMAT_TASK_STACK, SD_TASK_PRIORITY, SD_TASK_STACK, sd_writer_task(), sensor_task(), SENSOR_TASK_PRIORITY, SENSOR_TASK_STACK, and TAG.
Referenced by app_main().
task_manager_init()
esp_err_t task_manager_init (void)
Inicializa las colas principales del sistema.
Esta función crea las colas que serán usadas para intercambiar datos entre las tareas de FreeRTOS. Debe ejecutarse antes de crear las tareas del nodo.
Returns
ESP_OK si las colas fueron creadas correctamente.
ESP_FAIL si alguna cola no pudo inicializarse.
Inicializa las colas principales del sistema.
Esta función crea las dos colas principales usadas por el pipeline del nodo: una para transportar muestras crudas del sensor y otra para transportar registros listos para almacenamiento.
La lógica de esta inicialización es dejar preparados los canales de comunicación antes de lanzar cualquier tarea, evitando que una tarea empiece a ejecutarse sin que sus recursos de intercambio existan.
Returns
ESP_OK si ambas colas fueron creadas correctamente.
ESP_FAIL si alguna de las colas no pudo crearse.
Definition at line 220 of file task_manager.c.
References g_log_queue, g_raw_queue, LOG_QUEUE_LENGTH, RAW_QUEUE_LENGTH, and TAG.
Referenced by app_main().
Variable Documentation
g_log_queue
QueueHandle_t g_log_queue extern
Cola global para transportar registros listos para almacenamiento.
Esta cola comunica la tarea de procesamiento con la tarea encargada de escribir en la microSD. En ella se almacenan registros ya convertidos a formato de texto.
Cola global para transportar registros listos para almacenamiento.
En esta cola la tarea de formateo deposita estructuras del tipo log_record_t, ya convertidas a texto, para que la tarea de escritura las almacene en la SD.
Definition at line 57 of file task_manager.c.
Referenced by format_local_task(), sd_writer_task(), and task_manager_init().
g_raw_queue
QueueHandle_t g_raw_queue extern
Cola global para transportar muestras crudas del MPU6050.
Esta cola comunica la tarea de adquisición del sensor con la tarea de procesamiento o formateo. En ella se almacenan estructuras con lecturas completas del MPU6050.
Cola global para transportar muestras crudas del MPU6050.
En esta cola la tarea de lectura del sensor deposita estructuras del tipo mpu_raw_data_t para que luego sean procesadas por la tarea de formateo.
Definition at line 49 of file task_manager.c.
Referenced by format_local_task(), sensor_task(), and task_manager_init().