Nodo ESP32 MPU6050 + microSD: main/file_logger.h File Reference
file_logger.h File Reference
Interfaz pública del módulo de registro en archivo.
#include "esp_err.h"
#include "data_types.h"
Functions
esp_err_t file_logger_init (void)
Inicializa el módulo de escritura en archivo.
esp_err_t file_logger_write_record (const log_record_t *record)
Escribe un registro formateado en el archivo de log.
void file_logger_close (void)
Cierra el archivo de log actualmente abierto.
Detailed Description
Interfaz pública del módulo de registro en archivo.
Este archivo declara las funciones encargadas de inicializar el sistema de almacenamiento de registros en la microSD y de escribir datos formateados en el archivo de log del proyecto.
El módulo file_logger actúa como una capa intermedia entre las tareas que generan información y el driver de acceso a la tarjeta SD. Su objetivo es simplificar la escritura de registros y mantener separada la lógica de adquisición/procesamiento de la lógica de almacenamiento.
Definition in file file_logger.h.
Function Documentation
file_logger_close()
void file_logger_close (void)
Cierra el archivo de log actualmente abierto.
Esta función libera el recurso asociado al archivo de salida y deja el módulo en un estado seguro. Se utiliza al finalizar el proceso de registro o cuando se desea cerrar ordenadamente el acceso al archivo.
Esta función libera el manejador del archivo si se encuentra abierto y deja el puntero global en NULL para evitar accesos inválidos posteriores.
Se utiliza normalmente al finalizar el uso del logger o como parte de una rutina segura de cierre del sistema.
Definition at line 133 of file file_logger.c.
References g_log_file, and sdcard_close_file().
file_logger_init()
esp_err_t file_logger_init (void)
Inicializa el módulo de escritura en archivo.
Esta función prepara el archivo de log para comenzar a almacenar registros. Internamente verifica que la microSD esté montada, abre el archivo definido en la configuración del proyecto y, si corresponde, escribe el encabezado del archivo.
Debe ejecutarse antes de llamar a la función de escritura de registros.
Returns
ESP_OK si la inicialización fue exitosa.
ESP_FAIL si la SD no está montada, si el archivo no pudo abrirse o si falló la escritura del encabezado.
Inicializa el módulo de escritura en archivo.
Esta función verifica primero que la tarjeta microSD esté montada. Luego intenta abrir el archivo definido en la configuración del proyecto y, si aún no se ha hecho, escribe el encabezado del archivo CSV o TXT.
Su lógica es preparar el entorno de almacenamiento antes de que comiencen a llegar registros desde las tareas del sistema.
Returns
ESP_OK si el archivo quedó listo para escritura.
ESP_FAIL si la SD no está montada, si no se pudo abrir el archivo o si falló la escritura del encabezado.
Definition at line 62 of file file_logger.c.
References g_header_written, g_log_file, LOG_FILE_PATH, sdcard_append_line(), sdcard_close_file(), sdcard_is_mounted(), sdcard_open_log_file(), and TAG.
Referenced by sd_writer_task().
file_logger_write_record()
esp_err_t file_logger_write_record (const log_record_t * record)
Escribe un registro formateado en el archivo de log.
Esta función recibe una estructura de tipo log_record_t que contiene una línea de texto ya construida y lista para ser almacenada. El contenido es enviado al driver de la microSD para su escritura en el archivo.
Parameters
record Puntero al registro que se desea guardar.
Returns
ESP_OK si el registro fue escrito correctamente.
ESP_ERR_INVALID_ARG si el puntero recibido es nulo.
ESP_FAIL si el archivo no está disponible o si ocurre un error de escritura.
Esta función recibe una estructura con una línea de texto ya preparada para almacenamiento y la agrega al archivo previamente abierto.
Su lógica es simple: validar que el registro y el archivo sean válidos, y delegar la escritura real al driver de la microSD.
Parameters
record Puntero al registro que contiene la línea de texto a guardar.
Returns
ESP_OK si el registro fue escrito correctamente.
ESP_ERR_INVALID_ARG si el puntero recibido es nulo.
ESP_FAIL si el archivo no está abierto o si ocurre un error de escritura.
Definition at line 109 of file file_logger.c.
References g_log_file, log_record_t::line, sdcard_append_line(), and TAG.
Referenced by sd_writer_task().