Nodo ESP32 MPU6050 + microSD: main/main.c File Reference
main.c File Reference
Punto de entrada principal del nodo local con MPU6050 y microSD.
#include <stdio.h>
#include "esp_log.h"
#include "esp_err.h"
#include "task_manager.h"
#include "mpu6050_drv.h"
#include "sdcard_drv.h"
Functions
void app_main (void)
Función principal de la aplicación en ESP-IDF.
Variables
static const char * TAG = "APP"
Etiqueta usada para mensajes de depuración del módulo principal.
Detailed Description
Punto de entrada principal del nodo local con MPU6050 y microSD.
Este archivo contiene la función principal de arranque de la aplicación en ESP-IDF. Su responsabilidad es inicializar los módulos base del sistema y poner en marcha las tareas de FreeRTOS necesarias para la operación del nodo.
La lógica general de inicio es:
crear las colas de comunicación entre tareas,
inicializar el sensor MPU6050,
inicializar y montar la microSD,
crear las tareas encargadas de lectura, formateo y escritura,
y dejar el sistema ejecutándose de forma autónoma.
Este nodo trabaja de forma local, sin comunicación con otros ESP, y está orientado a adquirir datos del MPU6050 y almacenarlos en archivo.
Definition in file main.c.
Function Documentation
app_main()
void app_main (void)
Función principal de la aplicación en ESP-IDF.
Esta función es el punto de entrada del programa una vez el ESP32 ha arrancado. Se encarga de ejecutar en orden la inicialización del sistema.
Primero crea las colas que permitirán intercambiar datos entre las tareas. Luego inicializa el MPU6050 para habilitar la lectura del sensor, monta la microSD para preparar el almacenamiento y finalmente crea las tareas del sistema mediante el gestor de tareas.
Si alguna etapa falla, la función registra el error y detiene la secuencia de arranque para evitar que el sistema continúe en un estado inconsistente.
Note
Esta función no entra en un bucle infinito explícito porque, una vez creadas las tareas de FreeRTOS, el control principal queda delegado al planificador del sistema operativo.
Definition at line 50 of file main.c.
References mpu6050_init(), sdcard_init(), TAG, task_manager_create_tasks(), and task_manager_init().
Variable Documentation
TAG
const char* TAG = "APP" static
Etiqueta usada para mensajes de depuración del módulo principal.
Definition at line 29 of file main.c.