Nodo ESP32 MPU6050 + microSD: main/mpu6050_drv.h File Reference
mpu6050_drv.h File Reference
Interfaz pública del driver del sensor MPU6050.
#include "esp_err.h"
#include "data_types.h"
Functions
esp_err_t mpu6050_init (void)
Inicializa el sensor MPU6050.
esp_err_t mpu6050_read_raw (mpu_raw_data_t *out_data)
Lee una muestra del MPU6050 y la almacena en una estructura de salida.
Detailed Description
Interfaz pública del driver del sensor MPU6050.
Este archivo declara las funciones necesarias para inicializar el sensor MPU6050 y obtener muestras de aceleración, velocidad angular y temperatura.
El módulo está diseñado para trabajar sobre I2C dentro del entorno ESP-IDF y entregar los datos en una estructura común del proyecto, de modo que puedan ser procesados por otras tareas del sistema.
Definition in file mpu6050_drv.h.
Function Documentation
mpu6050_init()
esp_err_t mpu6050_init (void)
Inicializa el sensor MPU6050.
Esta función configura la comunicación I2C necesaria para acceder al sensor, verifica su identificación mediante el registro WHO_AM_I y lo saca del modo de bajo consumo para dejarlo listo para operar.
Debe ejecutarse una sola vez al iniciar el sistema, antes de intentar leer cualquier dato del sensor.
Returns
ESP_OK si el sensor fue inicializado correctamente.
Código de error si falla la configuración del bus I2C, la verificación del sensor o su activación.
Esta función prepara tanto la interfaz I2C como el propio sensor. Primero inicializa el bus maestro, luego lee el registro WHO_AM_I para comprobar la respuesta del dispositivo y finalmente escribe en PWR_MGMT_1 para sacar al MPU6050 del modo sleep.
La lógica de esta función garantiza que el sensor quede listo para comenzar a entregar datos crudos de aceleración, giroscopio y temperatura.
Returns
ESP_OK si el sensor fue inicializado correctamente.
Código de error si falla la inicialización del bus, la lectura de identificación o la escritura del registro de activación.
Definition at line 170 of file mpu6050_drv.c.
References mpu6050_i2c_master_init(), mpu6050_read_bytes(), MPU6050_REG_PWR_MGMT_1, MPU6050_REG_WHO_AM_I, MPU6050_WHO_AM_I_EXPECTED, mpu6050_write_byte(), and TAG.
Referenced by app_main().
mpu6050_read_raw()
esp_err_t mpu6050_read_raw (mpu_raw_data_t * out_data)
Lee una muestra del MPU6050 y la almacena en una estructura de salida.
Esta función obtiene los datos crudos del acelerómetro, giroscopio y temperatura, los convierte a unidades físicas y los guarda en una variable de tipo mpu_raw_data_t junto con una marca de tiempo.
Su propósito es ofrecer una lectura completa del estado instantáneo del sensor en un formato listo para ser procesado por el resto del sistema.
Parameters
out_data Puntero a la estructura donde se almacenará la muestra leída.
Returns
ESP_OK si la lectura fue exitosa.
ESP_ERR_INVALID_ARG si el puntero de salida es nulo.
Código de error si ocurre una falla durante la lectura por I2C.
Lee una muestra del MPU6050 y la almacena en una estructura de salida.
Esta función realiza una lectura continua de 14 bytes desde el registro ACCEL_XOUT_H. A partir de ese bloque obtiene:
aceleración en los ejes X, Y y Z,
temperatura interna,
velocidad angular en los ejes X, Y y Z.
Luego interpreta los bytes como enteros de 16 bits con signo y aplica los factores de escala por defecto del sensor al arrancar:
acelerómetro en rango ±2g,
giroscopio en rango ±250 °/s.
Finalmente también agrega una marca de tiempo en milisegundos usando el temporizador del sistema.
Parameters
out_data Puntero a la estructura donde se guardará la muestra convertida.
Returns
ESP_OK si la lectura y conversión fueron exitosas.
ESP_ERR_INVALID_ARG si el puntero de salida es nulo.
Código de error si la lectura I2C falla.
Definition at line 228 of file mpu6050_drv.c.
References mpu_raw_data_t::ax, mpu_raw_data_t::ay, mpu_raw_data_t::az, mpu_raw_data_t::gx, mpu_raw_data_t::gy, mpu_raw_data_t::gz, mpu6050_read_bytes(), MPU6050_REG_ACCEL_XOUT_H, mpu_raw_data_t::temperature, and mpu_raw_data_t::timestamp_ms.
Referenced by sensor_task().