Nodo ESP32 MPU6050 + microSD: main/sdcard_drv.h File Reference
sdcard_drv.h File Reference
Interfaz pública del driver de acceso a la microSD.
#include <stdio.h>
#include <stdbool.h>
#include "esp_err.h"
Functions
esp_err_t sdcard_init (void)
Inicializa la microSD y monta el sistema de archivos.
bool sdcard_is_mounted (void)
Consulta si la microSD está montada y lista para usarse.
FILE * sdcard_open_log_file (const char *path)
Abre un archivo en la microSD en modo append.
esp_err_t sdcard_append_line (FILE *file, const char *line)
Escribe una línea de texto en un archivo abierto.
void sdcard_close_file (FILE *file)
Cierra un archivo abierto en la microSD.
Detailed Description
Interfaz pública del driver de acceso a la microSD.
Este archivo declara las funciones necesarias para inicializar la tarjeta microSD, verificar su estado de montaje y realizar operaciones básicas sobre archivos, como abrirlos, escribir líneas de texto y cerrarlos.
El objetivo de este módulo es encapsular el acceso al sistema de archivos para que el resto del proyecto pueda trabajar con funciones simples y no dependa directamente de la configuración SPI ni del montaje del volumen.
Definition in file sdcard_drv.h.
Function Documentation
sdcard_append_line()
esp_err_t sdcard_append_line (FILE * file, const char * line)
Escribe una línea de texto en un archivo abierto.
Esta función agrega el contenido de la cadena recibida al archivo indicado y realiza un vaciado del buffer para asegurar que la información quede efectivamente enviada al sistema de archivos.
Parameters
file Puntero al archivo previamente abierto.
line Cadena de texto que se desea escribir.
Returns
ESP_OK si la línea fue escrita correctamente.
ESP_ERR_INVALID_ARG si alguno de los parámetros es nulo.
ESP_FAIL si ocurre un error en la escritura o sincronización.
Escribe una línea de texto en un archivo abierto.
Esta función escribe una cadena de texto en el archivo recibido y luego fuerza el vaciado del buffer con fflush() para asegurar que el contenido sea enviado efectivamente al sistema de archivos.
Su lógica es ofrecer una operación simple y segura para registrar datos línea por línea.
Parameters
file Puntero al archivo previamente abierto.
line Cadena de texto que se desea escribir.
Returns
ESP_OK si la línea fue escrita y sincronizada correctamente.
ESP_ERR_INVALID_ARG si alguno de los parámetros es nulo.
ESP_FAIL si ocurre un error en la escritura o en el vaciado del buffer.
Definition at line 194 of file sdcard_drv.c.
References TAG.
Referenced by file_logger_init(), and file_logger_write_record().
sdcard_close_file()
void sdcard_close_file (FILE * file)
Cierra un archivo abierto en la microSD.
Esta función libera el recurso asociado al archivo y finaliza de forma segura la sesión de escritura o lectura correspondiente.
Parameters
file Puntero al archivo que se desea cerrar.
Cierra un archivo abierto en la microSD.
Esta función valida que el puntero recibido no sea nulo y luego libera el recurso asociado al archivo mediante fclose().
Se utiliza para finalizar de forma segura una sesión de escritura.
Parameters
file Puntero al archivo que se desea cerrar.
Definition at line 224 of file sdcard_drv.c.
Referenced by file_logger_close(), and file_logger_init().
sdcard_init()
esp_err_t sdcard_init (void)
Inicializa la microSD y monta el sistema de archivos.
Esta función configura el bus SPI, intenta detectar la tarjeta y monta el sistema de archivos FAT en el punto de montaje definido por el driver.
Debe ejecutarse antes de cualquier operación de apertura o escritura de archivos.
Returns
ESP_OK si la tarjeta fue inicializada y montada correctamente.
Código de error si falla la inicialización del bus SPI o el montaje.
Inicializa la microSD y monta el sistema de archivos.
Esta función configura el host SPI, inicializa el bus físico usando los pines definidos en el proyecto y luego intenta montar la tarjeta SD en la ruta /sdcard.
La lógica interna sigue esta secuencia:
mostrar información de depuración de los pines usados,
configurar el montaje del sistema FAT,
preparar el host SPI y el bus físico,
inicializar el bus SPI,
asociar la tarjeta al pin CS,
montar la microSD en el sistema de archivos virtual del ESP32.
Si todo sale bien, se habilita la bandera interna g_sd_mounted y el sistema queda listo para abrir archivos.
Returns
ESP_OK si la tarjeta fue montada correctamente.
Código de error si falla la inicialización del SPI o el montaje de la SD.
Definition at line 71 of file sdcard_drv.c.
References g_card, g_sd_mounted, SD_SPI_CS, SD_SPI_MISO, SD_SPI_MOSI, SD_SPI_SCLK, and TAG.
Referenced by app_main().
sdcard_is_mounted()
bool sdcard_is_mounted (void)
Consulta si la microSD está montada y lista para usarse.
Esta función permite verificar desde otros módulos si el sistema de archivos ya está disponible antes de intentar abrir o escribir archivos.
Returns
true si la microSD está montada.
false si no está disponible o no ha sido inicializada correctamente.
Consulta si la microSD está montada y lista para usarse.
Esta función permite a otros módulos consultar si el sistema de archivos ya está disponible antes de intentar operar sobre archivos.
Returns
true si la tarjeta está montada.
false si la tarjeta aún no ha sido montada o falló la inicialización.
Definition at line 137 of file sdcard_drv.c.
References g_sd_mounted.
Referenced by file_logger_init().
sdcard_open_log_file()
FILE * sdcard_open_log_file (const char * path)
Abre un archivo en la microSD en modo append.
Esta función intenta abrir el archivo especificado en modo de añadido, de forma que el contenido nuevo se escriba al final del archivo sin sobrescribir los datos existentes.
Parameters
path Ruta completa del archivo que se desea abrir.
Returns
Puntero válido de tipo FILE* si la apertura fue exitosa.
NULL si la microSD no está montada o si falla la apertura del archivo.
Abre un archivo en la microSD en modo append.
Esta función verifica primero que la tarjeta esté montada. Si la SD está disponible, intenta abrir el archivo indicado en modo "a", lo que permite agregar contenido al final sin borrar los datos existentes.
Su lógica es preparar el acceso al archivo de salida que será usado por el sistema de registro.
Parameters
path Ruta completa del archivo que se desea abrir.
Returns
Puntero válido de tipo FILE* si la apertura fue exitosa.
NULL si la SD no está montada o si ocurre un error al abrir el archivo.
Definition at line 158 of file sdcard_drv.c.
References g_sd_mounted, and TAG.
Referenced by file_logger_init().